import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import UserAppHeader from "@/components/layout-components/user-app-header";
import UserAppSidebar from "@/components/layout-components/user-app-sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserAppHeader />
        <div className="flex">
          <UserAppSidebar className="hidden md:block z-10 border-solid border-black" />
          {children}
        </div>
      </body>
    </html>
  );
}
